version: '3'

services:
  container:
    image: mfe-container:latest
    build:
      context: ../../packages/container
      dockerfile: ../../docker/multi/Dockerfile.container
      args:
        - PUBLIC_URI=http://localhost
        - MARKETING_URI=http://localhost:8091
        - AUTH_URI=http://localhost:8092
        - DASHBOARD_URI=http://localhost:8093
    container_name: mfe-container
    ports:
      - 80:80

  marketing:
    image: mfe-marketing:latest
    build:
      context: ../../packages/marketing
      dockerfile: ../../docker/multi/Dockerfile
      args:
        - PUBLIC_URI=http://localhost:8091
    container_name: mfe-marketing
    ports:
      - 8091:80
  
  auth:
    image: mfe-auth:latest
    build:
      context: ../../packages/auth
      dockerfile: ../../docker/multi/Dockerfile
      args:
        - PUBLIC_URI=http://localhost:8092
    container_name: mfe-auth
    ports:
      - 8092:80
  
  dashboard:
    image: mfe-dashboard:latest
    build:
      context: ../../packages/dashboard
      dockerfile: ../../docker/multi/Dockerfile.dashboard
      args:
        - PUBLIC_URI=http://localhost:8093
    container_name: mfe-dashboard
    ports:
      - 8093:80